#!/usr/bin/python
# -*- coding: UTF-8 -*-

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
fig, ax = plt.subplots(1, 2, figsize=(6, 3))
# fig, ax = plt.subplots(nrows = 1, ncols = 2, figsize=(6, 3))

plt.show()
